export type ReportData = {
  id: string;
  company: string;
  ticker: string;
  sector: string;
  jurisdiction: string;
  date: string;
  duration: string;
  agentsRun: string;
  esgScore: number;
  rating: string;
  riskLevel: "HIGH" | "MEDIUM" | "LOW";
  pillars: { e: number; s: number; g: number };
  greenwashing: number;
  confidence: number;
  // LLM-variance confidence bands [low, high]. Empty when no variance
  // harness has been run yet.
  esgScoreBand?: [number, number];
  greenwashingBand?: [number, number];
  confidenceBand?: [number, number];
  bandMeta?: Record<string, unknown>;
  scope1: number;
  scope2: number;
  scope3: number;
  netZeroTarget: string;
  carbonBudgetYears: number;
  ieaGapPct?: number;
  claim: string;
  verdict: "CONTRADICTED" | "SUPPORTED" | "UNVERIFIABLE" | "INCONCLUSIVE";
  summary: string;
  topFindings: { kind: "red" | "amber" | "green"; text: string }[];
  contradictions: { severity: string; claim: string; evidence: string; source: string; impact: string; kind: string }[];
  regulatory: { framework: string; score: number; status: string; gap: string }[];
  regulatoryOverall: number;
  peers: { name: string; ticker: string; esg: number; gw: number; rating: string; marketCap: number; isFocus?: boolean }[];
  evidence: { type: string; domain: string; url: string; year: number; credibility: number; stance: string; excerpt: string; archive: string }[];
  greenwashingData?: any;
  shapDrivers?: { f: string; v: number }[];
  requiredAnnualRate?: number;
  companyImpliedRate?: number;
  alignmentStatus?: string;
  auditText?: string;
  auditSections?: { title: string; body: string }[];
  auditBrief?: Record<string, unknown> | null;
  rawReport?: Record<string, unknown> | null;
};
