"""
Regulatory Horizon Scanner Agent
Maps ESG claims against global and Indian regulations

Supported Regulations:
- INDIA: SEBI BRSR, MCA Companies Act, CPCB Environmental Compliance, RBI Green Finance
- EU: CSRD, EU Taxonomy, SFDR
- US: SEC Climate Rules, FTC Green Guides
- UK: FCA Anti-Greenwashing Rules, TCFD
- GLOBAL: GRI, SASB, ISSB, CDP, SBTi

Uses ChromaDB for regulation text storage and semantic search
"""

import json
import re
from typing import Dict, Any, List, Optional
from datetime import datetime
from core.llm_client import llm_client
from core.vector_store import vector_store
from config.agent_prompts import REGULATORY_COMPLIANCE_PROMPT


class RegulatoryHorizonScanner:
    """
    ESG Regulatory Compliance Scanner
    Verifies claims against global and Indian regulations
    """
    
    def __init__(self):
        self.name = "Regulatory Horizon Scanner"
        self.llm = llm_client
        self.vector_store = vector_store
        
        # Initialize regulation database
        self.regulations = self._initialize_regulations()
        
        print(f"✅ {self.name} initialized")
        print(f"   Loaded {len(self.regulations)} regulatory frameworks")
    
    def _initialize_regulations(self) -> Dict[str, Dict[str, Any]]:
        """Initialize comprehensive regulation database"""
        
        return {
            # =============================================
            # INDIAN REGULATIONS
            # =============================================
            "SEBI_BRSR": {
                "name": "SEBI BRSR (Business Responsibility and Sustainability Report)",
                "jurisdiction": "India",
                "authority": "Securities and Exchange Board of India",
                "effective_date": "2023-04-01",
                "applicability": "Top 1000 listed companies by market cap",
                "key_requirements": [
                    "Mandatory disclosure of Scope 1 and Scope 2 GHG emissions",
                    "Energy consumption from renewable and non-renewable sources",
                    "Water withdrawal, consumption, and discharge",
                    "Waste generated by type and disposal method",
                    "Employee well-being metrics and safety data",
                    "Value chain ESG assessment",
                    "BRSR Core assurance requirement from FY 2023-24"
                ],
                "penalties": {
                    "non_disclosure": "SEBI enforcement action, trading restrictions",
                    "false_disclosure": "Fraud investigation under SEBI Act"
                },
                "claim_validation_rules": [
                    {"pattern": "net zero|carbon neutral", "requirement": "Must disclose Scope 1, 2, 3 emissions with baseline"},
                    {"pattern": "renewable energy|clean energy", "requirement": "Must disclose % from renewable sources"},
                    {"pattern": "water positive|water neutral", "requirement": "Must disclose water withdrawal and recycling data"},
                    {"pattern": "zero waste|waste reduction", "requirement": "Must disclose waste by type and disposal method"}
                ]
            },
            
            "MCA_COMPANIES_ACT": {
                "name": "MCA Companies Act 2013 - ESG Provisions",
                "jurisdiction": "India",
                "authority": "Ministry of Corporate Affairs, India",
                "effective_date": "2013-08-29",
                "applicability": "All companies registered in India",
                "key_requirements": [
                    "Board Report must include CSR activities (Section 134)",
                    "CSR spending mandate - 2% of average net profits (Section 135)",
                    "Director responsibility for ESG oversight",
                    "Annual Return disclosure of energy conservation (Rule 8)",
                    "Secretarial Audit for listed companies"
                ],
                "penalties": {
                    "csr_non_compliance": "Transfer unspent amount to ESG fund, penalty up to ₹1 crore",
                    "false_disclosure": "Imprisonment up to 3 years, fine up to ₹25 lakh"
                },
                "claim_validation_rules": [
                    {"pattern": "csr|corporate social responsibility", "requirement": "Must have Board CSR committee, 2% spending mandate"},
                    {"pattern": "community investment|social impact", "requirement": "Must align with Schedule VII activities"}
                ]
            },
            
            "CPCB_EPA": {
                "name": "CPCB Environmental Compliance (EPA 1986)",
                "jurisdiction": "India",
                "authority": "Central Pollution Control Board / MoEFCC",
                "effective_date": "1986-11-19",
                "applicability": "All industrial units in India",
                "key_requirements": [
                    "Consent to Establish (CTE) and Consent to Operate (CTO)",
                    "Emission standards compliance for 17 categories",
                    "Effluent discharge standards",
                    "Hazardous waste management rules",
                    "Environmental audit and compliance reports",
                    "Real-time emission monitoring (OCEMS)"
                ],
                "penalties": {
                    "violation": "Imprisonment up to 5 years, fine up to ₹1 lakh per day",
                    "closure": "Production stoppage order"
                },
                "claim_validation_rules": [
                    {"pattern": "pollution free|zero discharge", "requirement": "Must have valid CTO and compliance certificates"},
                    {"pattern": "emission reduction|clean production", "requirement": "Must show CPCB compliance data"}
                ]
            },
            
            "RBI_GREEN_FINANCE": {
                "name": "RBI Green Finance Guidelines",
                "jurisdiction": "India",
                "authority": "Reserve Bank of India",
                "effective_date": "2023-01-01",
                "applicability": "All RBI regulated entities",
                "key_requirements": [
                    "Climate risk stress testing for banks",
                    "Green bond framework compliance",
                    "Disclosure of climate-related financial risks",
                    "Green taxonomy alignment for loans",
                    "Environmental and Social risk assessment in lending"
                ],
                "penalties": {
                    "non_compliance": "RBI regulatory action, restrictions on lending"
                },
                "claim_validation_rules": [
                    {"pattern": "green bond|sustainable finance", "requirement": "Must comply with RBI green bond framework"},
                    {"pattern": "climate risk|transition risk", "requirement": "Must disclose climate risk assessment"}
                ]
            },
            
            "INDIA_BEE_PAT": {
                "name": "BEE PAT Scheme (Perform, Achieve, Trade)",
                "jurisdiction": "India", 
                "authority": "Bureau of Energy Efficiency",
                "effective_date": "2012-04-01",
                "applicability": "Designated Consumers (high energy industries)",
                "key_requirements": [
                    "Specific Energy Consumption (SEC) targets",
                    "Energy audit by BEE accredited auditors",
                    "Energy Saving Certificates (ESCerts) trading",
                    "Mandatory reporting of energy consumption"
                ],
                "penalties": {
                    "non_achievement": "Purchase ESCerts from market, penalty"
                },
                "claim_validation_rules": [
                    {"pattern": "energy efficiency|energy saving", "requirement": "Must show PAT compliance if Designated Consumer"}
                ]
            },
            
            # =============================================
            # EU REGULATIONS
            # =============================================
            "EU_CSRD": {
                "name": "EU Corporate Sustainability Reporting Directive",
                "jurisdiction": "European Union",
                "authority": "European Commission",
                "effective_date": "2024-01-01",
                "applicability": "Large EU companies and listed SMEs, non-EU companies with EU revenue >€150M",
                "key_requirements": [
                    "Double materiality assessment (impact and financial)",
                    "ESRS (European Sustainability Reporting Standards) compliance",
                    "Scope 3 emissions disclosure",
                    "Biodiversity and ecosystem impact",
                    "Due diligence on value chain",
                    "Third-party limited assurance (moving to reasonable assurance)"
                ],
                "penalties": {
                    "non_compliance": "Member state penalties, market access restrictions",
                    "greenwashing": "Up to 4% of annual turnover"
                },
                "claim_validation_rules": [
                    {"pattern": "sustainable|sustainability", "requirement": "Must comply with ESRS double materiality"},
                    {"pattern": "value chain|supply chain esg", "requirement": "Must conduct value chain due diligence"},
                    {"pattern": "science based|sbti", "requirement": "Must show SBTi validation"}
                ]
            },
            
            "EU_TAXONOMY": {
                "name": "EU Taxonomy Regulation",
                "jurisdiction": "European Union",
                "authority": "European Commission",
                "effective_date": "2022-01-01",
                "applicability": "CSRD companies, financial market participants",
                "key_requirements": [
                    "Taxonomy alignment of economic activities",
                    "Substantial contribution to 1 of 6 environmental objectives",
                    "Do No Significant Harm (DNSH) criteria",
                    "Minimum social safeguards",
                    "Taxonomy-aligned revenue, CapEx, OpEx disclosure"
                ],
                "claim_validation_rules": [
                    {"pattern": "taxonomy aligned|eu taxonomy", "requirement": "Must meet substantial contribution and DNSH criteria"},
                    {"pattern": "green investment|sustainable investment", "requirement": "Must show taxonomy alignment percentage"}
                ]
            },
            
            "EU_SFDR": {
                "name": "EU Sustainable Finance Disclosure Regulation",
                "jurisdiction": "European Union",
                "authority": "European Commission",
                "effective_date": "2021-03-10",
                "applicability": "Financial market participants and advisers",
                "key_requirements": [
                    "ESG risk integration in investment process",
                    "Principal Adverse Impact (PAI) statements",
                    "Article 8 (promotes ESG) / Article 9 (sustainable objective) classification",
                    "Pre-contractual and periodic disclosures"
                ],
                "claim_validation_rules": [
                    {"pattern": "esg fund|sustainable fund", "requirement": "Must classify under SFDR Article 8 or 9"},
                    {"pattern": "impact investment", "requirement": "Must show Article 9 objective"}
                ]
            },
            
            # =============================================
            # US REGULATIONS  
            # =============================================
            "SEC_CLIMATE": {
                "name": "SEC Climate Disclosure Rules",
                "jurisdiction": "United States",
                "authority": "Securities and Exchange Commission",
                "effective_date": "2024-03-06",
                "applicability": "SEC registrants (public companies)",
                "key_requirements": [
                    "Material climate-related risks disclosure",
                    "GHG emissions (Scope 1, 2, material Scope 3)",
                    "Climate risk governance and management",
                    "Financial statement impact of climate risks",
                    "Climate targets and transition plans"
                ],
                "penalties": {
                    "non_disclosure": "SEC enforcement action",
                    "false_disclosure": "Securities fraud prosecution"
                },
                "claim_validation_rules": [
                    {"pattern": "climate risk|transition plan", "requirement": "Must file with SEC Form 10-K"},
                    {"pattern": "net zero|emission reduction", "requirement": "Must disclose in SEC filings with material assumptions"}
                ]
            },
            
            "FTC_GREEN_GUIDES": {
                "name": "FTC Green Guides",
                "jurisdiction": "United States",
                "authority": "Federal Trade Commission",
                "effective_date": "2012-10-01",
                "applicability": "All US businesses marketing green products",
                "key_requirements": [
                    "Environmental marketing claims must be truthful",
                    "Claims must be substantiated",
                    "Qualifications must be clear and prominent",
                    "Specific guidance on recyclable, biodegradable, carbon neutral claims"
                ],
                "penalties": {
                    "violation": "FTC enforcement action, consent orders, civil penalties"
                },
                "claim_validation_rules": [
                    {"pattern": "biodegradable|compostable", "requirement": "Must degrade within 1 year in customary disposal"},
                    {"pattern": "recyclable", "requirement": "Must be recyclable in substantial majority of communities"},
                    {"pattern": "carbon neutral|carbon offset", "requirement": "Must substantiate with reliable offsets"}
                ]
            },
            
            # =============================================
            # UK REGULATIONS
            # =============================================
            "UK_FCA_ANTIGREENWASHING": {
                "name": "FCA Anti-Greenwashing Rule",
                "jurisdiction": "United Kingdom",
                "authority": "Financial Conduct Authority",
                "effective_date": "2024-05-31",
                "applicability": "All FCA-authorised firms",
                "key_requirements": [
                    "Sustainability claims must be fair, clear, not misleading",
                    "Claims must be capable of substantiation",
                    "No cherry-picking or selective disclosure",
                    "Applies to ALL sustainability-related claims"
                ],
                "penalties": {
                    "violation": "FCA enforcement action, fines, restrictions"
                },
                "claim_validation_rules": [
                    {"pattern": "sustainable|green|ethical", "requirement": "Must be substantiated and not misleading"},
                    {"pattern": "esg|responsible investment", "requirement": "Must have clear methodology"}
                ]
            },
            
            "UK_TCFD": {
                "name": "UK TCFD Mandatory Disclosure",
                "jurisdiction": "United Kingdom",
                "authority": "HM Treasury / FCA",
                "effective_date": "2022-04-06",
                "applicability": "UK premium listed companies, large private companies",
                "key_requirements": [
                    "Governance of climate risks and opportunities",
                    "Strategy including scenario analysis",
                    "Risk management processes",
                    "Metrics and targets including GHG emissions"
                ],
                "claim_validation_rules": [
                    {"pattern": "climate strategy|tcfd", "requirement": "Must disclose 4 TCFD pillars"},
                    {"pattern": "scenario analysis|climate scenario", "requirement": "Must include 1.5°C and 2°C+ scenarios"}
                ]
            },
            
            # =============================================
            # GLOBAL FRAMEWORKS
            # =============================================
            "GHG_PROTOCOL": {
                "name": "GHG Protocol Corporate Standard",
                "jurisdiction": "Global",
                "authority": "WRI / WBCSD",
                "effective_date": "2001-01-01",
                "applicability": "Voluntary (de facto standard)",
                "key_requirements": [
                    "Scope 1, 2, 3 emissions inventory",
                    "Operational or financial control boundaries",
                    "Location-based and market-based Scope 2",
                    "15 Scope 3 categories",
                    "Base year recalculation policy"
                ],
                "claim_validation_rules": [
                    {"pattern": "scope 1|scope 2|scope 3", "requirement": "Must follow GHG Protocol methodology"},
                    {"pattern": "carbon footprint|ghg inventory", "requirement": "Must cover all material emission sources"}
                ]
            },
            
            "SBTI": {
                "name": "Science Based Targets initiative",
                "jurisdiction": "Global",
                "authority": "CDP, UNGC, WRI, WWF",
                "effective_date": "2015-01-01",
                "applicability": "Voluntary corporate targets",
                "key_requirements": [
                    "1.5°C or well-below 2°C pathway alignment",
                    "Scope 1, 2 mandatory, Scope 3 if >40% of emissions",
                    "5-10 year target timeframe",
                    "Annual progress reporting"
                ],
                "claim_validation_rules": [
                    {"pattern": "science based|sbti|1.5", "requirement": "Must have SBTi validated target"},
                    {"pattern": "paris aligned|paris agreement", "requirement": "Must show alignment pathway"}
                ]
            },
            
            "GRI_STANDARDS": {
                "name": "GRI Sustainability Reporting Standards",
                "jurisdiction": "Global",
                "authority": "Global Reporting Initiative",
                "effective_date": "2023-01-01",
                "applicability": "Voluntary (widely adopted)",
                "key_requirements": [
                    "Material topics disclosure",
                    "Sector-specific disclosures",
                    "Stakeholder engagement",
                    "Impact materiality assessment"
                ],
                "claim_validation_rules": [
                    {"pattern": "gri report|gri standards", "requirement": "Must follow GRI Universal Standards 2021"},
                    {"pattern": "materiality assessment", "requirement": "Must show stakeholder engagement process"}
                ]
            },
            
            "CDP": {
                "name": "CDP (Carbon Disclosure Project)",
                "jurisdiction": "Global",
                "authority": "CDP Non-profit",
                "effective_date": "2000-01-01",
                "applicability": "Investor/customer requested disclosure",
                "key_requirements": [
                    "Climate, Water, Forests questionnaires",
                    "GHG emissions disclosure",
                    "Climate risk and opportunity assessment",
                    "Supply chain engagement"
                ],
                "claim_validation_rules": [
                    {"pattern": "cdp score|cdp a list", "requirement": "Must submit annual CDP questionnaire"},
                    {"pattern": "supplier engagement", "requirement": "Must have supplier CDP program"}
                ]
            }
        }
    
    def scan_regulatory_compliance(self, company: str, claim: Dict[str, Any],
                                   evidence: List[Dict[str, Any]],
                                   jurisdiction: str = "India") -> Dict[str, Any]:
        """
        Scan claim against applicable regulations
        
        Args:
            company: Company name
            claim: ESG claim to verify
            evidence: Supporting evidence
            jurisdiction: Primary jurisdiction (India, EU, US, UK, Global)
        
        Returns:
            Comprehensive regulatory compliance assessment
        """
        
        print(f"\n{'='*60}")
        print(f"⚖️  AGENT: {self.name}")
        print(f"{'='*60}")
        print(f"Company: {company}")
        print(f"Jurisdiction: {jurisdiction}")
        print(f"Claim: {claim.get('claim_text', '')[:80]}...")
        
        claim_text = claim.get("claim_text", "").lower()
        evidence_text = self._combine_evidence(evidence)
        
        # 1. Identify applicable regulations
        print("🔍 Identifying applicable regulations...")
        applicable_regs = self._identify_applicable_regulations(claim_text, jurisdiction)
        
        # 2. Check compliance for each regulation
        print(f"⚖️ Checking compliance against {len(applicable_regs)} regulations...")
        compliance_results = []
        for reg_id in applicable_regs:
            result = self._check_regulation_compliance(reg_id, claim, evidence_text)
            compliance_results.append(result)
        
        # 3. LLM deep compliance analysis
        print("🤖 Running AI compliance analysis...")
        llm_analysis = self._llm_compliance_analysis(company, claim_text, evidence_text, applicable_regs)
        
        # 4. Identify regulatory risks
        print("⚠️ Identifying regulatory risks...")
        regulatory_risks = self._identify_regulatory_risks(compliance_results)
        
        # 5. Generate compliance score
        compliance_score = self._calculate_compliance_score(compliance_results)
        
        result = {
            "company": company,
            "claim_id": claim.get("claim_id"),
            "jurisdiction": jurisdiction,
            "applicable_regulations": [self.regulations[r]["name"] for r in applicable_regs],
            "compliance_results": compliance_results,
            "llm_analysis": llm_analysis,
            "regulatory_risks": regulatory_risks,
            "compliance_score": compliance_score,
            "recommendations": self._generate_compliance_recommendations(compliance_results),
            "upcoming_regulations": self._get_upcoming_regulations(jurisdiction)
        }
        
        print(f"\n✅ Regulatory scan complete:")
        print(f"   Applicable regulations: {len(applicable_regs)}")
        print(f"   Compliance score: {compliance_score['score']}/100")
        print(f"   Risk level: {compliance_score['risk_level']}")
        
        return result
    
    def _combine_evidence(self, evidence: List[Dict[str, Any]]) -> str:
        """Combine evidence into searchable text"""
        texts = []
        for ev in evidence[:15]:
            title = ev.get("title", "")
            snippet = ev.get("snippet", ev.get("relevant_text", ""))
            texts.append(f"{title}: {snippet}")
        return "\n\n".join(texts)[:8000]
    
    def _identify_applicable_regulations(self, claim_text: str, 
                                        jurisdiction: str) -> List[str]:
        """Identify regulations applicable to the claim"""
        
        applicable = []
        
        # Add jurisdiction-specific regulations
        jurisdiction_map = {
            "India": ["SEBI_BRSR", "MCA_COMPANIES_ACT", "CPCB_EPA", "RBI_GREEN_FINANCE", "INDIA_BEE_PAT"],
            "EU": ["EU_CSRD", "EU_TAXONOMY", "EU_SFDR"],
            "US": ["SEC_CLIMATE", "FTC_GREEN_GUIDES"],
            "UK": ["UK_FCA_ANTIGREENWASHING", "UK_TCFD"],
            "Global": ["GHG_PROTOCOL", "SBTI", "GRI_STANDARDS", "CDP"]
        }
        
        # Add primary jurisdiction regulations
        if jurisdiction in jurisdiction_map:
            applicable.extend(jurisdiction_map[jurisdiction])
        
        # Always check global frameworks
        applicable.extend(jurisdiction_map["Global"])
        
        # Check claim content for additional applicable regulations
        for reg_id, reg_data in self.regulations.items():
            if reg_id in applicable:
                continue
                
            for rule in reg_data.get("claim_validation_rules", []):
                if re.search(rule["pattern"], claim_text, re.IGNORECASE):
                    applicable.append(reg_id)
                    break
        
        return list(set(applicable))
    
    def _check_regulation_compliance(self, reg_id: str, claim: Dict[str, Any],
                                     evidence_text: str) -> Dict[str, Any]:
        """Check compliance with a specific regulation"""
        
        reg = self.regulations.get(reg_id, {})
        claim_text = claim.get("claim_text", "").lower()
        evidence_lower = evidence_text.lower()
        
        violations = []
        requirements_met = []
        requirements_unverified = []
        
        # Check claim validation rules
        for rule in reg.get("claim_validation_rules", []):
            pattern = rule["pattern"]
            requirement = rule["requirement"]
            
            if re.search(pattern, claim_text, re.IGNORECASE):
                # Claim triggers this rule - check if requirement is met
                requirement_keywords = requirement.lower().split()
                key_terms = [w for w in requirement_keywords if len(w) > 4][:5]
                
                if any(term in evidence_lower for term in key_terms):
                    requirements_met.append({
                        "triggered_by": pattern,
                        "requirement": requirement,
                        "status": "Likely Compliant"
                    })
                else:
                    requirements_unverified.append({
                        "triggered_by": pattern,
                        "requirement": requirement,
                        "status": "Cannot Verify - Evidence Insufficient"
                    })
        
        # Calculate compliance status
        total_rules = len(requirements_met) + len(requirements_unverified)
        if total_rules == 0:
            compliance_status = "Not Applicable"
            compliance_percentage = 100
        elif len(requirements_unverified) == 0:
            compliance_status = "Compliant"
            compliance_percentage = 100
        elif len(requirements_met) == 0:
            compliance_status = "Non-Compliant"
            compliance_percentage = 0
        else:
            compliance_status = "Partially Compliant"
            compliance_percentage = (len(requirements_met) / total_rules) * 100
        
        return {
            "regulation_id": reg_id,
            "regulation_name": reg.get("name"),
            "jurisdiction": reg.get("jurisdiction"),
            "authority": reg.get("authority"),
            "compliance_status": compliance_status,
            "compliance_percentage": round(compliance_percentage, 1),
            "requirements_met": requirements_met,
            "requirements_unverified": requirements_unverified,
            "violations": violations,
            "penalties": reg.get("penalties", {})
        }
    
    def _llm_compliance_analysis(self, company: str, claim_text: str,
                                 evidence_text: str, applicable_regs: List[str]) -> Dict[str, Any]:
        """Use LLM for deep compliance analysis"""
        
        reg_summaries = []
        for reg_id in applicable_regs[:5]:  # Top 5 regulations
            reg = self.regulations.get(reg_id, {})
            reg_summaries.append(f"- {reg.get('name')}: {reg.get('key_requirements', [])[:3]}")
        
        prompt = f"""{REGULATORY_COMPLIANCE_PROMPT}

COMPANY: {company}
CLAIM: {claim_text}

APPLICABLE REGULATIONS:
{chr(10).join(reg_summaries)}

EVIDENCE:
{evidence_text[:4000]}

Analyze regulatory compliance risks. Return JSON."""
        
        response = self.llm.call_with_fallback(prompt, use_gemini_first=True)
        
        if not response:
            return {"analysis_performed": False, "error": "LLM call failed"}
        
        try:
            cleaned = re.sub(r'```\s*json?\s*', '', response)
            cleaned = re.sub(r'```\s*', '', cleaned)
            start = cleaned.find('{')
            end = cleaned.rfind('}') + 1
            if start != -1 and end > start:
                return json.loads(cleaned[start:end])
        except:
            pass
        
        return {"analysis_performed": True, "raw_analysis": response[:500]}
    
    def _identify_regulatory_risks(self, compliance_results: List[Dict]) -> List[Dict[str, Any]]:
        """Identify key regulatory risks"""
        
        risks = []
        
        for result in compliance_results:
            if result["compliance_status"] in ["Non-Compliant", "Partially Compliant"]:
                risk_level = "High" if result["compliance_status"] == "Non-Compliant" else "Medium"
                
                risks.append({
                    "regulation": result["regulation_name"],
                    "jurisdiction": result["jurisdiction"],
                    "risk_level": risk_level,
                    "unverified_requirements": [r["requirement"] for r in result["requirements_unverified"]],
                    "potential_penalties": result["penalties"]
                })
        
        # Sort by risk level
        risk_order = {"High": 0, "Medium": 1, "Low": 2}
        risks.sort(key=lambda x: risk_order.get(x["risk_level"], 2))
        
        return risks
    
    def _calculate_compliance_score(self, compliance_results: List[Dict]) -> Dict[str, Any]:
        """Calculate overall compliance score"""
        
        if not compliance_results:
            return {"score": 0, "risk_level": "Unknown", "detail": "No regulations checked"}
        
        # Filter out "Not Applicable" results
        applicable_results = [r for r in compliance_results if r["compliance_status"] != "Not Applicable"]
        
        if not applicable_results:
            return {"score": 100, "risk_level": "Low", "detail": "No regulations triggered"}
        
        # Calculate weighted average
        total_score = sum(r["compliance_percentage"] for r in applicable_results)
        avg_score = total_score / len(applicable_results)
        
        # Determine risk level
        if avg_score >= 80:
            risk_level = "Low"
        elif avg_score >= 50:
            risk_level = "Medium"
        else:
            risk_level = "High"
        
        return {
            "score": round(avg_score, 1),
            "risk_level": risk_level,
            "regulations_checked": len(applicable_results),
            "fully_compliant": sum(1 for r in applicable_results if r["compliance_status"] == "Compliant"),
            "partially_compliant": sum(1 for r in applicable_results if r["compliance_status"] == "Partially Compliant"),
            "non_compliant": sum(1 for r in applicable_results if r["compliance_status"] == "Non-Compliant")
        }
    
    def _generate_compliance_recommendations(self, compliance_results: List[Dict]) -> List[str]:
        """Generate actionable compliance recommendations"""
        
        recommendations = []
        
        for result in compliance_results:
            if result["compliance_status"] == "Non-Compliant":
                recommendations.append(
                    f"[CRITICAL] {result['regulation_name']}: Address unverified requirements immediately"
                )
            elif result["compliance_status"] == "Partially Compliant":
                for req in result["requirements_unverified"][:2]:
                    recommendations.append(
                        f"[PARTIAL] {result['regulation_name']}: {req['requirement']}"
                    )
        
        # Add proactive recommendations
        if not recommendations:
            recommendations.append("[OK] Current disclosures appear compliant with applicable regulations")
            recommendations.append("[RECOMMEND] Consider voluntary third-party assurance for enhanced credibility")
        
        return recommendations[:10]
    
    def _get_upcoming_regulations(self, jurisdiction: str) -> List[Dict[str, Any]]:
        """Get upcoming regulatory changes"""
        
        upcoming = [
            {
                "regulation": "SEBI BRSR Core - Reasonable Assurance",
                "jurisdiction": "India",
                "effective": "FY 2024-25",
                "impact": "Mandatory external assurance of BRSR Core indicators"
            },
            {
                "regulation": "EU CSRD - Value Chain Due Diligence",
                "jurisdiction": "EU",
                "effective": "2025",
                "impact": "Extended due diligence requirements for large companies"
            },
            {
                "regulation": "ISSB S1/S2 Standards",
                "jurisdiction": "Global",
                "effective": "2024 (voluntary), 2025+ (adoption)",
                "impact": "Global baseline for sustainability disclosure"
            },
            {
                "regulation": "India Green Taxonomy",
                "jurisdiction": "India",
                "effective": "2025-26 (expected)",
                "impact": "Classification of sustainable activities for India"
            }
        ]
        
        # Filter by relevance to jurisdiction
        if jurisdiction == "India":
            return [u for u in upcoming if u["jurisdiction"] in ["India", "Global"]]
        elif jurisdiction == "EU":
            return [u for u in upcoming if u["jurisdiction"] in ["EU", "Global"]]
        else:
            return upcoming


# Global instance
regulatory_scanner = RegulatoryHorizonScanner()

def get_regulatory_scanner() -> RegulatoryHorizonScanner:
    """Get global regulatory scanner instance"""
    return regulatory_scanner
