"""
Patch script: replaces the Section 9 (Deception Pattern Analysis) block
in professional_report_generator.py with the refactored version.

Lines 1720–1761 (1-indexed) are replaced.
"""
import sys

PATH = r"c:\Users\Mahi\major\core\professional_report_generator.py"

NEW_BLOCK = (
    "        green = state.get(\"greenwishing_analysis\") or {}\n"
    "        climate = state.get(\"climatebert_analysis\") or v[\"agents\"].get(\"climatebert_analysis\", {}).get(\"output\", {})\n"
    "        overall_dec = safe_get(green, \"overall_deception_risk\", \"score\", default=0)\n"
    "        overall_lvl = str(safe_get(green, \"overall_deception_risk\", \"level\", default=\"LOW\")).upper()\n"
    "        section7 = [major, \"SECTION 9: DECEPTION PATTERN ANALYSIS\", major]\n"
    "        section7.append(f\"  Overall Deception Risk:  {self._fmt_score1(overall_dec)}/100  ({overall_lvl})\")\n"
    "        if isinstance(overall_dec, (int, float)) and abs(float(overall_dec) - float(v[\"gw_score\"])) > 30:\n"
    "            section7.append(\n"
    "                self._wrap_paragraph(\n"
    "                    f\"  NOTE: Deception Risk ({self._fmt_score1(overall_dec)}) and Greenwashing Score \"\n"
    "                    f\"({v['gw_score']:.1f}) diverge materially. \"\n"
    "                    \"Low deception + high greenwashing = disclosure gap, not intentional manipulation. \"\n"
    "                    \"Risks are driven by omission and execution shortfalls rather than confirmed misrepresentation.\",\n"
    "                    width=80,\n"
    "                )\n"
    "            )\n"
    "        section7.append(\"\")\n"
    "\n"
    "        # --- Tactic Table (consistent labels throughout) ---\n"
    "        section7.append(f\"  {'Tactic':<24} {'Status':<14} {'Score':<8} {'Evidence':<32}\")\n"
    "        section7.append(\"  \" + \"-\" * 81)\n"
    "        gw = green.get(\"greenwishing\", {}) if isinstance(green, dict) else {}\n"
    "        gh = green.get(\"greenhushing\", {}) if isinstance(green, dict) else {}\n"
    "        sd = green.get(\"selective_disclosure\", {}) if isinstance(green, dict) else {}\n"
    "\n"
    "        # Greenwishing row\n"
    "        _gw_lvl = str(gw.get(\"risk_level\", \"LOW\")).upper()\n"
    "        _gw_status = \"Risk: \" + _gw_lvl.title()\n"
    "        _gw_count = len(gw.get(\"findings\", gw.get(\"indicators_found\", [])) or [])\n"
    "        section7.append(\n"
    "            f\"  {'Greenwishing':<24} {_gw_status:<14} {str(gw.get('score', '0')):<8} \"\n"
    "            f\"{str(_gw_count) + ' indicator(s) detected':<32}\"\n"
    "        )\n"
    "        # Greenhushing row\n"
    "        _gh_lvl = str(gh.get(\"risk_level\", \"LOW\")).upper()\n"
    "        _gh_status = \"Risk: \" + _gh_lvl.title()\n"
    "        _gh_missing = gh.get(\"missing_fields\", 0)\n"
    "        section7.append(\n"
    "            f\"  {'Greenhushing':<24} {_gh_status:<14} {str(gh.get('score', '0')):<8} \"\n"
    "            f\"{str(_gh_missing) + ' missing field(s)':<32}\"\n"
    "        )\n"
    "        # Selective disclosure row — no Yes/No, no N/A\n"
    "        _sd_present = \"Present\" if sd.get(\"detected\") else \"Not Detected\"\n"
    "        _sd_count = len(sd.get(\"findings\", sd.get(\"patterns\", [])) or [])\n"
    "        _sd_evidence = str(_sd_count) + \" pattern(s) identified\" if _sd_count > 0 else \"No patterns identified\"\n"
    "        section7.append(\n"
    "            f\"  {'Selective disclosure':<24} {_sd_present:<14} {'\\u2014':<8} {_sd_evidence:<32}\"\n"
    "        )\n"
    "        # Carbon tunnel vision row — no Yes/No, no N/A\n"
    "        _ctv_present = \"Present\" if len(missing_scopes) >= 2 else \"Not Detected\"\n"
    "        _ctv_evidence = str(len(missing_scopes)) + \" scope(s) undisclosed\" if len(missing_scopes) >= 2 else \"All scopes covered\"\n"
    "        section7.append(\n"
    "            f\"  {'Carbon tunnel vision':<24} {_ctv_present:<14} {'\\u2014':<8} {_ctv_evidence:<32}\"\n"
    "        )\n"
    "        section7.append(\"  \" + \"-\" * 81)\n"
    "\n"
    "        # --- Top Indicators (meaningful, deduplicated, max 3) ---\n"
    "        indicators = (gw.get(\"findings\") or gw.get(\"indicators_found\") or []) if isinstance(gw, dict) else []\n"
    "        _meaningful: list = []\n"
    "        _seen: set = set()\n"
    "        for item in indicators:\n"
    "            if isinstance(item, dict):\n"
    "                txt = str(item.get(\"description\") or item.get(\"type\") or \"\").replace(\"_\", \" \").strip()\n"
    "            else:\n"
    "                txt = str(item).replace(\"_\", \" \").strip()\n"
    "            if not txt or txt.lower() in {\"indicator detected\", \"n/a\", \"none\", \"unknown\", \"\"}:\n"
    "                continue\n"
    "            txt_key = txt.lower()[:60]\n"
    "            if txt_key in _seen:\n"
    "                continue\n"
    "            _seen.add(txt_key)\n"
    "            _meaningful.append(txt)\n"
    "            if len(_meaningful) == 3:\n"
    "                break\n"
    "\n"
    "        if _meaningful:\n"
    "            section7.append(\"\\n  Top indicators detected:\")\n"
    "            for m in _meaningful:\n"
    "                section7.append(f\"    - {m}\")\n"
    "        else:\n"
    "            section7.append(\"\\n  Top indicators: None \\u2014 no high-confidence deception signals found in this run.\")\n"
    "\n"
    "        # --- Deception vs. Greenwashing Insight ---\n"
    "        section7.append(\"\")\n"
    "        _dec = float(overall_dec) if isinstance(overall_dec, (int, float)) else 0.0\n"
    "        _gw_score_val = float(v[\"gw_score\"]) if isinstance(v.get(\"gw_score\"), (int, float)) else 0.0\n"
    "        if _dec < 30 and _gw_score_val >= 50:\n"
    "            _interp_block = (\n"
    "                \"Interpretation: Low deception risk combined with elevated greenwashing risk signals that \"\n"
    "                \"identified concerns are primarily driven by disclosure gaps and execution shortfalls rather than \"\n"
    "                \"deliberate misrepresentation. The company does not appear to be intentionally misleading \"\n"
    "                \"investors, but material omissions reduce transition credibility.\"\n"
    "            )\n"
    "        elif _dec >= 50:\n"
    "            _interp_block = (\n"
    "                \"Interpretation: Elevated deception risk is driven by active rhetorical patterns \\u2014 claims are \"\n"
    "                \"framed in ways that go beyond what the underlying evidence supports. This warrants closer \"\n"
    "                \"scrutiny of forward-looking commitments and target methodology.\"\n"
    "            )\n"
    "        else:\n"
    "            _interp_block = (\n"
    "                \"Interpretation: Deception signals are within the low-to-moderate range. Residual risk is \"\n"
    "                \"attributable to standard disclosure gaps rather than confirmed manipulative framing.\"\n"
    "            )\n"
    "        section7.append(self._wrap_paragraph(_interp_block, width=80))\n"
    "\n"
    "        # --- ClimateBERT NLP Signal (optional supporting block) ---\n"
    "        cb_score = safe_get(climate, \"claim_analysis\", \"greenwashing_detection\", \"risk_score\",\n"
    "                            default=safe_get(climate, \"greenwashing_risk\", default=None))\n"
    "        cb_level = str(safe_get(climate, \"claim_analysis\", \"greenwashing_detection\", \"risk_level\",\n"
    "                                default=safe_get(climate, \"risk_level\", default=\"\"))).upper()\n"
    "        _clim_rel = safe_get(climate, \"claim_analysis\", \"climate_relevance\", \"score\",\n"
    "                             default=safe_get(climate, \"climate_relevance\", default=None))\n"
    "        c_claim = safe_get(climate, \"comparison\", \"claim_greenwashing_score\",\n"
    "                           default=safe_get(climate, \"claim_score\", default=None))\n"
    "        c_ev    = safe_get(climate, \"comparison\", \"evidence_greenwashing_score\",\n"
    "                           default=safe_get(climate, \"evidence_score\", default=None))\n"
    "        # Only display when the NLP block carries genuine signal variance\n"
    "        _nlp_has_signal = (\n"
    "            isinstance(cb_score, (int, float)) and cb_score > 0\n"
    "            and isinstance(c_claim, (int, float)) and isinstance(c_ev, (int, float))\n"
    "        )\n"
    "        if _nlp_has_signal:\n"
    "            section7.append(\"\\n  NLP Supporting Signal (ClimateBERT):\")\n"
    "            # Suppress raw relevance score when it is constant / uninformative (> 95)\n"
    "            if isinstance(_clim_rel, (int, float)) and _clim_rel > 95:\n"
    "                section7.append(\"    Climate Relevance:    High climate relevance detected\")\n"
    "            elif isinstance(_clim_rel, (int, float)):\n"
    "                section7.append(f\"    Climate Relevance:    {self._fmt_score1(_clim_rel)} /100\")\n"
    "            # Claim vs evidence framing comparison \\u2014 narrative, not raw scores\n"
    "            _claim_gap = float(c_claim) - float(c_ev)\n"
    "            if _claim_gap > 10:\n"
    "                _lang_signal = \"Claim language is notably more promotional than the supporting evidence.\"\n"
    "            elif _claim_gap > 3:\n"
    "                _lang_signal = \"Claim language is slightly more optimistic than the supporting evidence.\"\n"
    "            elif _claim_gap < -5:\n"
    "                _lang_signal = \"Evidence language is more promotional than the formal claim language.\"\n"
    "            else:\n"
    "                _lang_signal = \"Claim language and evidence language are broadly consistent.\"\n"
    "            section7.append(f\"    NLP Signal:           {_lang_signal}\")\n"
    "            # Safe conflict handling \\u2014 never surface contradicting verdict labels\n"
    "            _sys_high = _dec >= 50 or overall_lvl in {\"HIGH\", \"CRITICAL\"}\n"
    "            _nlp_high = cb_level in {\"HIGH\", \"CRITICAL\"} or (isinstance(cb_score, (int, float)) and cb_score >= 60)\n"
    "            if _sys_high != _nlp_high:\n"
    "                section7.append(\n"
    "                    \"    Note: NLP signal suggests more promotional language than evidence supports; \"\n"
    "                    \"treat as a supplementary indicator alongside the structured deception scores above.\"\n"
    "                )\n"
    "            # ClimateBERT's own interpretation text (if non-generic)\n"
    "            _cb_interp = safe_get(climate, \"comparison\", \"interpretation\", default=\"\")\n"
    "            if _cb_interp and len(str(_cb_interp)) > 20 and \"reviewed for consistency\" not in str(_cb_interp).lower():\n"
    "                section7.append(f\"    Supporting context:   {str(_cb_interp)[:120]}\")\n"
    "\n"
    "        # --- Concluding Risk Summary ---\n"
    "        section7.append(\"\")\n"
    "        _top_tactics: list = []\n"
    "        if _gw_lvl in {\"HIGH\", \"CRITICAL\", \"MEDIUM\", \"MODERATE\"}:\n"
    "            _top_tactics.append(\"greenwishing\")\n"
    "        if _gh_lvl in {\"HIGH\", \"CRITICAL\", \"MEDIUM\", \"MODERATE\"}:\n"
    "            _top_tactics.append(\"greenhushing\")\n"
    "        if sd.get(\"detected\"):\n"
    "            _top_tactics.append(\"selective disclosure\")\n"
    "        if len(missing_scopes) >= 2:\n"
    "            _top_tactics.append(\"carbon tunnel vision\")\n"
    "        if not _top_tactics:\n"
    "            _top_tactics.append(\"no dominant tactic detected\")\n"
    "        _tactic_str = \", \".join(_top_tactics)\n"
    "        section7.append(\n"
    "            self._wrap_paragraph(\n"
    "                f\"Overall, deception risk is assessed as {overall_lvl}, with primary concern(s) driven by: \"\n"
    "                f\"{_tactic_str}. This should be interpreted alongside the greenwashing score \"\n"
    "                f\"({v['gw_score']:.1f}/100) and any regulatory or contradiction signals raised in earlier sections.\",\n"
    "                width=80,\n"
    "            )\n"
    "        )\n"
    "        section7.append(\"\\n\" + major)\n"
)

with open(PATH, encoding="utf-8") as f:
    lines = f.readlines()

# Replace lines 1720-1761 (0-indexed 1719-1760 inclusive = 42 lines)
START = 1719   # 0-indexed, inclusive
END   = 1761   # 0-indexed, exclusive (line 1762 stays)

new_lines = lines[:START] + [NEW_BLOCK] + lines[END:]

with open(PATH, "w", encoding="utf-8", newline="") as f:
    f.writelines(new_lines)

print(f"Patched: replaced lines {START+1}-{END} with refactored Section 9 block.")
print(f"New total lines: {len(new_lines)}")
